#!/bin/bash
#
# This tool greps a defined directory(~/Documents/TIL/) for .yml files.  It takes a regex pattern and builds
# an aggregated file from the .yml files that match the regex.  Note: that it attempts to use logical grouping for brevity.
#
# NOTE: You can manually create sections in your notes with top level dividers of: '---'
#   Sections will be pulled out together whenever a regex matches a subset of that section.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$script_dir")"

search_yaml_files(){
  local pattern="$1"
  local directory=$(toml $REPO_DIR/config.toml note.note_dir)
  local filetype=$(toml $REPO_DIR/config.toml note.filetype)
  local temp_file="/tmp/note_temp.${filetype}"

  if [ ! -d "$directory" ]; then
    echo "$directory does not exist, create note directory? (It can be changed in config.toml)"
    select yn in "Yes" "No"; do 
      case $yn in
        Yes ) mkdir -p "$directory"; break;;
        No ) exit;;
      esac
    done
  fi

  find "$directory" -type f -name "*${filetype}" -print0 | while IFS= read -r -d '' file; do
    awk -v pattern="$pattern" -v file=".$file" -f ${REPO_DIR}/src/awk/grep.awk ".$file" >> "$temp_file"
  done

  # Display the concatenated sections using less
  if [[ -s "$temp_file" ]]; then
    ## if file type md and glow installed, use glow 
    if command -v glow &>/dev/null && filetype == ".md"; then
      echo "Using glow"
      glow $temp_file 
    elif command -v bat &>/dev/null; then
      echo "Using bat"
      bat --theme gruvbox-dark --decorations never --paging always $temp_file 
    else
      echo "bat not installed, defaulting to less"
      less "$temp_file"
    fi
  else
    echo "No matches found."
  fi

  # Clean up temporary file
  rm "$temp_file"

}

search_yaml_files "$1" "$2"
